CHARACTER_NAME_MAPPING = {
    # Галактические Легенды
    "lord vader": "Lord Vader",
    "lv": "Lord Vader",
    "jedi master kenobi": "Jedi Master Kenobi",
    "jmk": "Jedi Master Kenobi",
    "supreme leader kylo ren": "Supreme Leader Kylo Ren",
    "slkr": "Supreme Leader Kylo Ren",
    "rey": "Rey",
    "rey scavenger": "Rey",
    "rey jedi training": "Rey (Jedi Training)",
    "rjt": "Rey (Jedi Training)",
    "jedi master luke skywalker": "Jedi Master Luke Skywalker",
    "jml": "Jedi Master Luke Skywalker",
    "jabba the hutt": "Jabba the Hutt",
    "jabba": "Jabba the Hutt",
    "leia organa": "Leia Organa",
    "leia": "Leia Organa",
    
    # Ситхи и Темные
    "darth vader": "Darth Vader",
    "vader": "Darth Vader",
    "darth revan": "Darth Revan",
    "darth malak": "Darth Malak",
    "darth traya": "Darth Traya",
    "darth nihilus": "Darth Nihilus",
    "darth sion": "Darth Sion",
    "darth maul": "Darth Maul",
    "maul": "Darth Maul",
    "count dooku": "Count Dooku",
    "dooku": "Count Dooku",
    "emperor palpatine": "Emperor Palpatine",
    "palpatine": "Emperor Palpatine",
    "darth sidious": "Darth Sidious",
    "sidious": "Darth Sidious",
    
    # Джедаи и Светлые
    "commander luke skywalker": "Commander Luke Skywalker",
    "cls": "Commander Luke Skywalker",
    "jedi knight luke skywalker": "Jedi Knight Luke Skywalker",
    "jkls": "Jedi Knight Luke Skywalker",
    "jedi knight revan": "Jedi Knight Revan",
    "jkr": "Jedi Knight Revan",
    "general skywalker": "General Skywalker",
    "gas": "General Skywalker",
    "grand master yoda": "Grand Master Yoda",
    "gmy": "Grand Master Yoda",
    "hermit yoda": "Hermit Yoda",
    "hoda": "Hermit Yoda",
    "general kenobi": "General Kenobi",
    "gk": "General Kenobi",
    "obi wan kenobi": "Obi-Wan Kenobi",
    "obiwan": "Obi-Wan Kenobi",
    "old ben kenobi": "Old Ben Kenobi",
    "old ben": "Old Ben Kenobi",
    "qui gon jinn": "Qui-Gon Jinn",
    "quigon": "Qui-Gon Jinn",
    "mace windu": "Mace Windu",
    "mace": "Mace Windu",
    "anakin skywalker": "Anakin Skywalker",
    "anakin": "Anakin Skywalker",
    "ahsoka tano": "Ahsoka Tano",
    "ahsoka": "Ahsoka Tano",
    "commander ahsoka tano": "Commander Ahsoka Tano",
    "cat": "Commander Ahsoka Tano",
    "padme amidala": "Padmé Amidala",
    "padme": "Padmé Amidala",
    
    # Персонажи Империи
    "general hux": "General Hux",
    "hux": "General Hux",
    "admiral piett": "Admiral Piett",
    "piett": "Admiral Piett",
    "moff gideon": "Moff Gideon",
    "gideon": "Moff Gideon",
    "grand admiral thrawn": "Grand Admiral Thrawn",
    "thrawn": "Grand Admiral Thrawn",
    "grand moff tarkin": "Grand Moff Tarkin",
    "tarkin": "Grand Moff Tarkin",
    "dark trooper": "Dark Trooper",
    "darktrooper": "Dark Trooper",
    "death trooper": "Death Trooper",
    "range trooper": "Range Trooper",
    "shoretrooper": "Shoretrooper",
    "snowtrooper": "Snowtrooper",
    
    # Охотники за головами
    "jango fett": "Jango Fett",
    "jango": "Jango Fett",
    "boba fett": "Boba Fett",
    "boba": "Boba Fett",
    "boba fett scion of jango": "Boba Fett, Scion of Jango",
    "scion of jango": "Boba Fett, Scion of Jango",
    "the mandalorian": "The Mandalorian",
    "mando": "The Mandalorian",
    "beskar mando": "The Mandalorian (Beskar Armor)",
    "the mandalorian beskar armor": "The Mandalorian (Beskar Armor)",
    "bossk": "Bossk",
    "greef karga": "Greef Karga",
    "greef": "Greef Karga",
    "krrsantan": "Krrsantan",
    "black krrsantan": "Krrsantan",
    "dengar": "Dengar",
    "ig-88": "IG-88",
    "ig88": "IG-88",
    "zam wesell": "Zam Wesell",
    "embo": "Embo",
    
    # Дроиды
    "c-3po": "C-3PO",
    "c3po": "C-3PO",
    "r2-d2": "R2-D2",
    "r2d2": "R2-D2",
    "bb-8": "BB-8",
    "bb8": "BB-8",
    "k-2so": "K-2SO",
    "k2so": "K-2SO",
    "ig-11": "IG-11",
    "ig11": "IG-11",
    "b1 battle droid": "B1 Battle Droid",
    "b1": "B1 Battle Droid",
    "b2 super battle droid": "B2 Super Battle Droid",
    "b2": "B2 Super Battle Droid",
    "droideka": "Droideka",
    
    # Другие фракции
    "starkiller": "Starkiller",
    "cal kestis": "Cal Kestis",
    "cal": "Cal Kestis",
    "general grievous": "General Grievous",
    "grievous": "General Grievous",
    "mother talzin": "Mother Talzin",
    "talzin": "Mother Talzin",
    "asajj ventress": "Asajj Ventress",
    "ventress": "Asajj Ventress",
    "merrin": "Merrin",
    "great mothers": "Great Mothers",
    "nightsister zombie": "Nightsister Zombie",
    "old daka": "Old Daka",
    "daka": "Old Daka",
    "geonosian brood alpha": "Geonosian Brood Alpha",
    "brood alpha": "Geonosian Brood Alpha",
    "geonosian soldier": "Geonosian Soldier",
    "geonosian spy": "Geonosian Spy",
    "wat tambor": "Wat Tambor",
    "wat": "Wat Tambor",
    "chewbacca": "Chewbacca",
    "chewie": "Chewbacca",
    "chewbacca legendary": "Chewbacca",
    
    # Повстанцы
    "hera syndulla": "Hera Syndulla",
    "hera": "Hera Syndulla",
    "kanan jarrus": "Kanan Jarrus",
    "kanan": "Kanan Jarrus",
    "ezra bridger": "Ezra Bridger",
    "ezra": "Ezra Bridger",
    "ezra exile": "Ezra (Exile)",
    "sabine wren": "Sabine Wren",
    "sabine": "Sabine Wren",
    "garazeb zeb orrelios": "Garazeb \"Zeb\" Orrelios",
    "zeb": "Garazeb \"Zeb\" Orrelios",
    "chopper": "Chopper",
    "cara dune": "Cara Dune",
    "cara": "Cara Dune",
    "jyn erso": "Jyn Erso",
    "jyn": "Jyn Erso",
    "cassian andor": "Cassian Andor",
    "cassian": "Cassian Andor",
    "chirrut imwe": "Chirrut Îmwe",
    "chirrut": "Chirrut Îmwe",
    "baze malbus": "Baze Malbus",
    "baze": "Baze Malbus",
    "bodhi rook": "Bodhi Rook",
    "pao": "Pao",
    "bistan": "Bistan",
    
    # Эвоки
    "wicket": "Wicket",
    "chief chirpa": "Chief Chirpa",
    "paploo": "Paploo",
    "teebo": "Teebo",
    "logray": "Logray",
    "ewok scout": "Ewok Scout",
    "ewok elder": "Ewok Elder",
    "princess kneesa": "Princess Kneesaa",
    "kneesa": "Princess Kneesaa",
    
    # Клоны
    "captain rex": "Captain Rex",
    "rex": "Captain Rex",
    "ct-7567 rex": "CT-7567 \"Rex\"",
    "ct-5555 fives": "CT-5555 \"Fives\"",
    "fives": "CT-5555 \"Fives\"",
    "ct-210408 echo": "CT-21-0408 \"Echo\"",
    "echo": "CT-21-0408 \"Echo\"",
    "arc trooper": "ARC Trooper",
    "arc": "ARC Trooper",
    "clone sergeant": "Clone Sergeant - Phase I",
    "cody": "CC-2224 \"Cody\"",
    
    # Bad Batch
    "bad batch hunter": "Hunter",
    "hunter": "Hunter",
    "bad batch wrecker": "Wrecker",
    "wrecker": "Wrecker",
    "bad batch tech": "Tech",
    "tech": "Tech",
    "bad batch echo": "Echo",
    "bad batch omega": "Omega",
    "omega": "Omega",
    "crosshair": "Crosshair (Scarred)",
    
    # Другие
    "enfy nest": "Enfys Nest",
    "nest": "Enfys Nest",
    "qira": "Qi'ra",
    "l3-37": "L3-37",
    "young han solo": "Young Han Solo",
    "young lando": "Young Lando Calrissian",
    "vandor chewbacca": "Vandor Chewbacca",
    "tusken raider": "Tusken Raider",
    "tusken warrior": "Tusken Warrior",
    "tusken chieftain": "Tusken Chieftain",
    "tusken shaman": "Tusken Shaman",
    "jawa": "Jawa",
    "jawas": "Jawa",
    "jawa engineer": "Jawa Engineer",
    "jawa scavenger": "Jawa Scavenger",
    "nute gunray": "Nute Gunray",
    "poggle the lesser": "Poggle the Lesser",
    "sun fac": "Sun Fac",
    "magnaguard": "IG-100 MagnaGuard",
    "sith trooper": "Sith Trooper",
    "sith marauder": "Sith Marauder",
    "sith assassin": "Sith Assassin",
    "imperial super commando": "Imperial Super Commando",
    "gar saxon": "Gar Saxon",
    "the armorer": "The Armorer",
    "armorer": "The Armorer",
    "kuill": "Kuiil",
    "ig-90": "IG-90",
    "ig90": "IG-90",
}


def normalize_character_name(name):
    """Нормализует имя персонажа для поиска"""
    name_lower = name.lower().strip()
    
    # Прямое совпадение
    if name_lower in CHARACTER_NAME_MAPPING:
        return CHARACTER_NAME_MAPPING[name_lower]
    
    # Частичное совпадение
    for key, value in CHARACTER_NAME_MAPPING.items():
        if key in name_lower or name_lower in key:
            return value
    
    # Возвращаем имя с заглавной буквы
    return ' '.join(word.capitalize() for word in name_lower.split())